### ISSUE TITLE
[Idea] Add etherchain to extension

### ISSUE THREAD

**Issue by enzomtpYT** [philippe-git/ethereum-gas-prices-browser-extension#4]
Hi ! I was searching for an extension that gives me the gas price of etherchain like yours, i can't find any, and i would like if you could add etherchain to your extension !

I got some link to help you out :
Official link : https://www.etherchain.org/tools/gasPriceOracle
Api : https://www.etherchain.org/api/gasPriceOracle

**Comment by philippe-git** [comment]
Closing in favor of #5
